### ISSUE TITLE
URLs in user profile should be converted to external links

### ISSUE THREAD

**Issue by jasonhemann** [clowdr-app/clowdr-web-app#247] opened 2020-08-28 13:14 UTC
Right now, if you leave off the protocol in your URL string, this is instead interpreted as a subpage within the current website.

**Comment by EdNutting** [comment] 2020-08-28 13:22
There was some use of this by authors to link direct to program items, but that can easily be achieved by using fully-qualified URLs. So this seems like a sensible change to me. Also, it we should probably make sure that all external links open in a new tab/window by default.

**Comment by mattmccutchen** [comment] 2020-08-28 19:33
Partial duplicate of #214.

**Comment by EdNutting** [comment] 2020-11-06 22:33
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(Notably this issue was also resolved in the new UI by enforcing that website links must be full URLs).

**Closed by EdNutting** 2020-11-06 22:33 UTC
