### ISSUE TITLE
Clowdr Inception

### ISSUE THREAD

**Issue by jasonhemann** [clowdr-app/clowdr-web-app#235] opened 2020-08-24 17:52 UTC
Hi,

I accidentally caused a Clowdr Inception. 

![Screen Shot 2020-08-24 at 13 47 29](https://user-images.githubusercontent.com/1329370/91078425-99a7d600-e610-11ea-9ff6-bbb9f8910726.jpg)

I _believe_ what I did was: attempt to enter a Zoom meeting, but that attempt failed because the host had locked the meeting (the host was me, I did it.) in Zoom. 

Both the inner and outer versions of the site are active.

**Comment by mattmccutchen** [comment] 2020-08-24 19:31
Duplicate of #118?

**Comment by EdNutting** [comment] 2020-11-06 22:37
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

**Closed by EdNutting** 2020-11-06 22:37 UTC
