### ISSUE TITLE
Participants cannot unmute their mics in breakout rooms or private chats

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr-web-app#136] opened 2020-08-13 15:28 UTC
When talking to a participant, I can see them unmuted, they see themselves as muted and there is no audio (tried safari and chrome, tried re-setting the media permissions on chrome, tried moving over different rooms, both of us logged out and logged in)

**Comment by jon-bell** [comment] 2020-08-13 15:29
Can you provide more details to reproduce this? Is it possible that the other participant had the wrong audio input device selected?

**Comment by bcpierce00** [comment] 2020-08-13 15:29
I also had an issue with sound this time: When I first joined the Clowdr part of the training, neither mic nor speakers were working for me.  Switching from Safari to Chrome fixed it this time.  I suspect restarting Safari might also have worked.

**Comment by sweirich** [comment] 2020-08-13 15:30
We should also add this to the troubleshooting part of the Clowdr user manual.

**Comment by bcpierce00** [comment] 2020-08-13 15:35
Hanneli and I just noticed that there may be a common thread here: It is likely that both I and the participant she was talking to were joining Clowdr from two different browsers at the same time.

**Comment by hannelita** [comment] 2020-08-13 15:35
@jon-bell It is not the case it was the wrong input... I did an extensive test

**Comment by jon-bell** [comment] 2020-08-13 15:37
Is it always the same other person who you are not hearing audio from, or have you experienced it with multiple people? Can you check the browser javascript console on both sides and note if there are any errors?

**Comment by bcpierce00** [comment] 2020-08-13 15:37
I was getting no audio at all.

**Comment by bcpierce00** [comment] 2020-08-13 15:53
Will make sure to look at the JS console if this happens again.

**Comment by bcpierce00** [comment] 2020-08-15 11:24
Marking this as Fixed? because we need more information to investigate further.

**Comment by EdNutting** [comment] 2020-11-06 23:05
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(In the new UI, we overhauled the Video Room experience and fixed various issues like this).

**Closed by EdNutting** 2020-11-06 23:05 UTC
Labels: Bug, Fixed?
