### ISSUE TITLE
Clowdr in multiple tabs

### ISSUE THREAD

**Issue by jasonhemann** [clowdr-app/clowdr-web-app#172] opened 2020-08-18 14:08 UTC
If, from within a conference's Clowdr instance, I open a Clowdr link in a new tab this second contextual chat opens and works, but messages sent from the older tab to the older contextual chat silently fail to send. This somewhat surprised me.

Attempting to access the same room (chat) via two different tabs yields the following message:

````
Error: unable to acquire camera
We were not able to acquire access to your camera and/or microphone. You must have a webcam and allow Clowdr access to it in order to join this call. Please double check that your webcam is plugged in, then refresh this page. If you continue to have difficulties, please be sure that you have allowed Clowdr access to your camera and microphone by following these instructions:
Safari: Go to the 'Safari' Menu, then select 'Settings for this website' and be sure that both camera and microphone are set to 'allow'.
Chrome: Go to chrome://settings/content, then select this website and be sure that camera and microphone are both set to 'Allow'. After completing these steps, please refresh the page to try again.

Internal error message: TwilioError: Participant disconnected because of duplicate identity
````

**Comment by jon-bell** [comment] 2020-08-18 14:10
Would you please send the links to the pages that you were accessing, your browser vendor and OS vendor?

**Comment by jasonhemann** [comment] 2020-08-18 14:38
OSX 10.15.6, Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by jon-bell** [comment] 2020-08-18 14:51
And, lastly, would you please send the links to the pages that you were accessing? I have very limited cycles to spend fixing bugs here, and anything that you can do to make it more likely that I can reproduce the bug that you found makes it far more likely that I can fix this, and others.

**Comment by jasonhemann** [comment] 2020-08-18 15:26
Yes, quite.

From, for instance [Lobby](https://icfp2020.clowdr.org/lobby), if I right-click Open-in-New-Tab on a paper, [e.g.](https://icfp2020.clowdr.org/program/lQtuSG74px/cwlC0lFv1O), I then have two tabs in the same conference with different contextual chats on the RHS.

**Comment by bcpierce00** [comment] 2020-08-18 15:31
Just to make sure I understand: There were two separate issues in your original report, yes?  messages not sending when Clowdr is open in multiple tabs, and can't be in two video chat spaces at once?  the second is intended behavior; the first not.

**Comment by jasonhemann** [comment] 2020-08-18 15:44
@bcpierce00, let me apologize and be more precise. I believe I report two symptoms of the same underlying cause. In most instances, opening a second Clowdr window opens _without_ the RHS contextual chat. That looks to me like the intended behavior. 

If you follow precisely [these steps](https://github.com/clowdr-app/clowdr-web-app/issues/172#issuecomment-675547459_) however, you can cause Clowdr to open a second tab to a second page with a *second* contextual chat window. Unlike in the former case, this latter, second contextual chat window works and is enabled and behaves like the real deal. What was *un*expected is that the first contextual RHS chat still looks just like it did before, functional. However, *sending* messages via this chat just fails silently. That silent failure to send is the first half of what I was reporting.

Now, suppose further that, after opening this new, second tab, I then use this new, second tab I've just opened to navigate in Clowdr _back_ to the original room I just left. (My reasoning: "I wonder if chat in the first tab would work again if I navigate back in the second...?") What happens, however, is that if you do navigate back like this, you get the Twilio error message I [mentioned](https://github.com/clowdr-app/clowdr-web-app/issues/172#issue-681072654). This is the second half of my report. I believe this second part is just further twisting the knife into the issue of the first part.

**Comment by bcpierce00** [comment] 2020-08-18 16:01
The basic functionality of posting messages from multiple tabs work for me. No let me try your precise script, Jason...

![image](https://user-images.githubusercontent.com/7014411/90536758-7a113900-e14a-11ea-8905-bf4e43cd9289.png)

**Comment by bcpierce00** [comment] 2020-08-18 16:08
Hmmm.  I think what I did was what you described.

I think (1) and (2) are different things.  Clowdr only allows one window to be streaming video at a time; this is expected behavior. Posting to multiple text channels from different windows should work, and if it doesn't we should fix it. Jason, if you can reproduce this behavior, can you please tell us exactly which text channels you were trying to post to?

**Comment by jasonhemann** [comment] 2020-08-18 18:24
Well, thank you all for the attention to this, and I sure hope it's worth the time you're investing. I was in Lobby and then the Haskell paper chat "Graded Monad ...." I attach a version of what I'm doing and seeing. And my apologies if this is all expected behavior. 


![a-gif-bug](https://user-images.githubusercontent.com/1329370/90550853-83a49c00-e15e-11ea-947c-d1c0bbbdbe9d.gif)

**Comment by bcpierce00** [comment] 2020-08-19 00:14
Bug confirmed!  Thank for the detailed report.

Here's what I see in the console of the window where the message didn't get sent:
![image](https://user-images.githubusercontent.com/7014411/90577624-7522a880-e18f-11ea-8b19-419b42c60e6b.png)

**Comment by jon-bell** [comment] 2020-08-19 17:38
This is now fixed: you can chat from multiple tabs. If you try to open the same video call twice, you'll get kicked out of one of them. As long as your browser supports sharing the camera with multiple tabs, you can be in different video calls in different tabs (but we certainly wouldn't suggest it).

**Closed by jon-bell** 2020-08-19 17:38 UTC
Labels: Bug, Medium priority
